(should= (elaborate '42)
         ''42)
(should= (elaborate '#f)
         ''#f)
(should= (elaborate ''())
         ''())
(should= (elaborate '(begin (write x) (lambda (y) (+ x y))))
         '((lambda (v thunk) (thunk))
           (write x)
           (lambda () (lambda (y) (+ x y)))))
(should= (elaborate '(begin (if x y z)))
         '(%unless x (lambda () z) (lambda () y)))
(should= (elaborate '(lambda ()
                       (local ((define (for-each f xs)
                                 (if (null? xs)
                                     '()
                                     (begin (f (car xs))
                                            (for-each f (cdr xs))))))
                         for-each)))
         '(lambda ()
            (letrec ((for-each
                      (lambda (f xs)
                        (%unless (null? xs)
                                 (lambda ()
                                   ((lambda (v thunk) (thunk))
                                    (f (car xs))
                                    (lambda () (for-each f (cdr xs)))))
                                 (lambda () '())))))
              for-each)))
